apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepforge-data
  namespace: deepforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: managed-premium  # Azure AKS
  # storageClassName: gp3              # AWS EKS
