import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type { WikiStructure } from "../types.js";

export interface WikiPage {
  path: string;
  title: string;
  number: string;
  content: string;
}

export function assembleWiki(
  structure: WikiStructure,
  pages: WikiPage[],
  outputDir: string,
): void {
  mkdirSync(outputDir, { recursive: true });

  // Generate index.md
  const indexContent = buildIndex(structure, pages);
  writeFileSync(join(outputDir, "index.md"), indexContent);

  // Write pages
  for (const page of pages) {
    const fullPath = join(outputDir, page.path);
    mkdirSync(dirname(fullPath), { recursive: true });

    const header = `# ${page.number}. ${page.title}\n\n`;
    const nav = buildPageNav(page, pages);
    writeFileSync(fullPath, header + page.content + "\n\n---\n\n" + nav);
  }
}

function buildIndex(structure: WikiStructure, pages: WikiPage[]): string {
  let md = `# ${structure.title}\n\n`;
  md += `${structure.description}\n\n`;
  md += `## Table of Contents\n\n`;

  for (const section of structure.sections) {
    const page = pages.find((p) => p.number === section.number);
    if (page) {
      md += `- [${section.number}. ${section.title}](${page.path})\n`;
    } else {
      md += `- ${section.number}. ${section.title}\n`;
    }

    for (const sub of section.subsections) {
      const subPage = pages.find((p) => p.number === sub.number);
      if (subPage) {
        md += `  - [${sub.number}. ${sub.title}](${subPage.path})\n`;
      } else {
        md += `  - ${sub.number}. ${sub.title}\n`;
      }
    }
  }

  md += `\n---\n\n*Generated by [Deepforge](https://github.com/deepforge)*\n`;
  return md;
}

function buildPageNav(current: WikiPage, pages: WikiPage[]): string {
  const idx = pages.indexOf(current);
  const parts: string[] = [];

  parts.push("[← Table of Contents](index.md)");

  if (idx > 0) {
    const prev = pages[idx - 1];
    parts.push(`[← ${prev.number}. ${prev.title}](${prev.path})`);
  }
  if (idx < pages.length - 1) {
    const next = pages[idx + 1];
    parts.push(`[${next.number}. ${next.title} →](${next.path})`);
  }

  return parts.join(" | ");
}

export function pagePathFromNumber(number: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `${number}-${slug}.md`;
}
