import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type { WikiStructure, GraphStats } from "../types.js";

export interface WikiPage {
  path: string;
  title: string;
  number: string;
  content: string;
}

export interface AssembleOptions {
  stats?: GraphStats;
  /** Repo URL — embedded in wiki for resync link */
  repoUrl?: string;
  /** Controller base URL — for the resync button */
  controllerUrl?: string;
}

export function assembleWiki(
  structure: WikiStructure,
  pages: WikiPage[],
  outputDir: string,
  options?: AssembleOptions,
): void {
  mkdirSync(outputDir, { recursive: true });

  const indexContent = buildIndex(structure, pages, options?.stats);
  writeFileSync(join(outputDir, "index.md"), indexContent);

  for (const page of pages) {
    const fullPath = join(outputDir, page.path);
    mkdirSync(dirname(fullPath), { recursive: true });

    const header = `# ${page.number}. ${page.title}\n\n`;
    const nav = buildPageNav(page, pages, structure);
    writeFileSync(fullPath, header + page.content + "\n\n---\n\n" + nav);
  }

  // Generate docsify files for browseable wiki
  writeFileSync(join(outputDir, "_sidebar.md"), buildSidebar(structure, pages));
  writeFileSync(
    join(outputDir, "index.html"),
    buildDocsifyHtml(structure.title, options?.repoUrl, options?.controllerUrl),
  );
  writeFileSync(join(outputDir, ".nojekyll"), "");
}

function buildIndex(
  structure: WikiStructure,
  pages: WikiPage[],
  stats?: GraphStats,
): string {
  let md = `# ${structure.title}\n\n`;
  md += `${structure.description}\n\n`;

  if (stats) {
    md += `## Project Statistics\n\n`;
    md += `| Metric | Count |\n`;
    md += `|--------|-------|\n`;
    md += `| Source Files | ${stats.fileCount} |\n`;
    md += `| Symbols | ${stats.nodeCount} |\n`;
    md += `| Relationships | ${stats.edgeCount} |\n`;

    const langs = Object.entries(stats.filesByLanguage)
      .sort((a, b) => b[1] - a[1])
      .map(([l, c]) => `${l} (${c})`)
      .join(", ");
    md += `| Languages | ${langs} |\n`;
    md += `\n`;

    const kindEntries = Object.entries(stats.nodesByKind)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8);
    if (kindEntries.length > 0) {
      md += `### Symbol Breakdown\n\n`;
      md += `| Kind | Count |\n`;
      md += `|------|-------|\n`;
      for (const [kind, count] of kindEntries) {
        md += `| ${kind} | ${count} |\n`;
      }
      md += `\n`;
    }
  }

  md += `## Table of Contents\n\n`;

  for (const section of structure.sections) {
    const page = pages.find((p) => p.number === section.number);
    if (page) {
      md += `- [${section.number}. ${section.title}](${page.path})`;
    } else {
      md += `- ${section.number}. ${section.title}`;
    }
    md += ` — ${section.description}\n`;

    for (const sub of section.subsections) {
      const subPage = pages.find((p) => p.number === sub.number);
      if (subPage) {
        md += `  - [${sub.number}. ${sub.title}](${subPage.path})`;
      } else {
        md += `  - ${sub.number}. ${sub.title}`;
      }
      md += ` — ${sub.description}\n`;
    }
  }

  md += `\n---\n\n*Generated by [Deepforge](https://github.com/deepforge) — ${new Date().toISOString().split("T")[0]}*\n`;
  return md;
}

function buildPageNav(
  current: WikiPage,
  pages: WikiPage[],
  structure: WikiStructure,
): string {
  const idx = pages.indexOf(current);
  const lines: string[] = [];

  lines.push("**Navigation:**\n");
  lines.push("[← Table of Contents](index.md)");

  if (idx > 0) {
    const prev = pages[idx - 1];
    lines.push(` | [← ${prev.number}. ${prev.title}](${prev.path})`);
  }
  if (idx < pages.length - 1) {
    const next = pages[idx + 1];
    lines.push(` | [${next.number}. ${next.title} →](${next.path})`);
  }

  // Add a mini TOC of sibling pages
  const currentSection = current.number.split(".")[0];
  const siblings = pages.filter(
    (p) =>
      p !== current &&
      p.number.startsWith(currentSection + ".") &&
      p.number.split(".").length === 2,
  );
  if (siblings.length > 0) {
    lines.push("\n\n**In this section:**");
    for (const s of siblings) {
      lines.push(`\n- [${s.number}. ${s.title}](${s.path})`);
    }
  }

  return lines.join("");
}

function buildSidebar(structure: WikiStructure, pages: WikiPage[]): string {
  let md = `- [Home](index.md)\n`;
  for (const section of structure.sections) {
    const page = pages.find((p) => p.number === section.number);
    const link = page ? `(${page.path})` : "";
    md += `- [${section.number}. ${section.title}]${link}\n`;
    for (const sub of section.subsections) {
      const subPage = pages.find((p) => p.number === sub.number);
      const subLink = subPage ? `(${subPage.path})` : "";
      md += `  - [${sub.number}. ${sub.title}]${subLink}\n`;
    }
  }
  return md;
}

function buildDocsifyHtml(title: string, repoUrl?: string, controllerUrl?: string): string {
  const generatedAt = new Date().toISOString();

  // Build the resync banner — only if we know the controller URL
  const bannerCss = `
    #deepforge-banner {
      position: fixed; top: 0; right: 0; z-index: 9999;
      display: flex; align-items: center; gap: 12px;
      padding: 8px 16px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 12px; color: #666;
      background: rgba(255,255,255,0.95);
      border-bottom-left-radius: 8px;
      box-shadow: -2px 2px 8px rgba(0,0,0,0.1);
    }
    #deepforge-banner .resync-btn {
      padding: 4px 12px; background: #3F51B5; color: white;
      border: none; border-radius: 4px; cursor: pointer;
      font-size: 12px; text-decoration: none;
    }
    #deepforge-banner .resync-btn:hover { background: #303F9F; }`;

  const bannerHtml =
    repoUrl && controllerUrl
      ? `
  <div id="deepforge-banner">
    <span style="opacity:0.7">Last synced: ${new Date(generatedAt).toLocaleDateString()} ${new Date(generatedAt).toLocaleTimeString()}</span>
    <a class="resync-btn" href="${controllerUrl}/?repo=${encodeURIComponent(repoUrl)}" title="Re-generate wiki from latest source">&#x21bb; Resync</a>
  </div>`
      : "";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="deepforge:generated-at" content="${generatedAt}">
  ${repoUrl ? `<meta name="deepforge:repo-url" content="${repoUrl}">` : ""}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple.css">
  <style>
    :root {
      --base-font-size: 15px;
      --theme-color: #3F51B5;
      --sidebar-width: 280px;
    }
    .markdown-section pre > code { font-size: 13px; }
    ${bannerCss}
  </style>
</head>
<body>
  ${bannerHtml}
  <div id="app"></div>
  <script>
    window.$docsify = {
      name: '${title.replace(/'/g, "\\'")}',
      loadSidebar: true,
      subMaxLevel: 3,
      search: 'auto',
      auto2top: true,
      mergeNavbar: true,
      homepage: 'index.md',
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-csharp.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-typescript.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-json.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docsify-mermaid@2/dist/docsify-mermaid.js"></script>
</body>
</html>`;
}

export function pagePathFromNumber(number: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `${number}-${slug}.md`;
}
