import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type { WikiStructure, GraphStats } from "../types.js";

export interface WikiPage {
  path: string;
  title: string;
  number: string;
  content: string;
}

export interface AssembleOptions {
  stats?: GraphStats;
}

export function assembleWiki(
  structure: WikiStructure,
  pages: WikiPage[],
  outputDir: string,
  options?: AssembleOptions,
): void {
  mkdirSync(outputDir, { recursive: true });

  const indexContent = buildIndex(structure, pages, options?.stats);
  writeFileSync(join(outputDir, "index.md"), indexContent);

  for (const page of pages) {
    const fullPath = join(outputDir, page.path);
    mkdirSync(dirname(fullPath), { recursive: true });

    const header = `# ${page.number}. ${page.title}\n\n`;
    const nav = buildPageNav(page, pages, structure);
    writeFileSync(fullPath, header + page.content + "\n\n---\n\n" + nav);
  }
}

function buildIndex(
  structure: WikiStructure,
  pages: WikiPage[],
  stats?: GraphStats,
): string {
  let md = `# ${structure.title}\n\n`;
  md += `${structure.description}\n\n`;

  if (stats) {
    md += `## Project Statistics\n\n`;
    md += `| Metric | Count |\n`;
    md += `|--------|-------|\n`;
    md += `| Source Files | ${stats.fileCount} |\n`;
    md += `| Symbols | ${stats.nodeCount} |\n`;
    md += `| Relationships | ${stats.edgeCount} |\n`;

    const langs = Object.entries(stats.filesByLanguage)
      .sort((a, b) => b[1] - a[1])
      .map(([l, c]) => `${l} (${c})`)
      .join(", ");
    md += `| Languages | ${langs} |\n`;
    md += `\n`;

    const kindEntries = Object.entries(stats.nodesByKind)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8);
    if (kindEntries.length > 0) {
      md += `### Symbol Breakdown\n\n`;
      md += `| Kind | Count |\n`;
      md += `|------|-------|\n`;
      for (const [kind, count] of kindEntries) {
        md += `| ${kind} | ${count} |\n`;
      }
      md += `\n`;
    }
  }

  md += `## Table of Contents\n\n`;

  for (const section of structure.sections) {
    const page = pages.find((p) => p.number === section.number);
    if (page) {
      md += `- [${section.number}. ${section.title}](${page.path})`;
    } else {
      md += `- ${section.number}. ${section.title}`;
    }
    md += ` — ${section.description}\n`;

    for (const sub of section.subsections) {
      const subPage = pages.find((p) => p.number === sub.number);
      if (subPage) {
        md += `  - [${sub.number}. ${sub.title}](${subPage.path})`;
      } else {
        md += `  - ${sub.number}. ${sub.title}`;
      }
      md += ` — ${sub.description}\n`;
    }
  }

  md += `\n---\n\n*Generated by [Deepforge](https://github.com/deepforge) — ${new Date().toISOString().split("T")[0]}*\n`;
  return md;
}

function buildPageNav(
  current: WikiPage,
  pages: WikiPage[],
  structure: WikiStructure,
): string {
  const idx = pages.indexOf(current);
  const lines: string[] = [];

  lines.push("**Navigation:**\n");
  lines.push("[← Table of Contents](index.md)");

  if (idx > 0) {
    const prev = pages[idx - 1];
    lines.push(` | [← ${prev.number}. ${prev.title}](${prev.path})`);
  }
  if (idx < pages.length - 1) {
    const next = pages[idx + 1];
    lines.push(` | [${next.number}. ${next.title} →](${next.path})`);
  }

  // Add a mini TOC of sibling pages
  const currentSection = current.number.split(".")[0];
  const siblings = pages.filter(
    (p) =>
      p !== current &&
      p.number.startsWith(currentSection + ".") &&
      p.number.split(".").length === 2,
  );
  if (siblings.length > 0) {
    lines.push("\n\n**In this section:**");
    for (const s of siblings) {
      lines.push(`\n- [${s.number}. ${s.title}](${s.path})`);
    }
  }

  return lines.join("");
}

export function pagePathFromNumber(number: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `${number}-${slug}.md`;
}
